intersection_coords: [0, 0]
max_simulation_steps: 500
simulation_step_length: 0.1
mcts_time: 200  # mcts time budget in ms

sumo_binary: "/opt/homebrew/opt/sumo/share/sumo"
sumo_cfg: "./data/2x4_intersection.sumocfg"

trip_info_out: "./out/tripinfo.xml"
collisions_out: "./out/collisions.xml"
statistics_out: "./out/statistics.xml"

passing_order_fcfs: "fcfs"
passing_order_mcts: "mcts"
passing_order_gurobi: "gurobi"
passing_order_mode: "gurobi"

num_vehicles: 50
num_routes: 8
colliding_routes: [[0, 4], [0, 6], [0, 7], [1, 4], [2, 4], [2, 6], [2, 5], [3, 6]]

# https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#speed_mode_0xb3
veh_mode: 32  # no checks enabled
veh_safe_mode: 32

veh_speed_default: 13.88  # ~50km/h
veh_speed_adjust: 8.88  # -5m/s
veh_speed_intersection: 6.94  # ~25km/h

veh_state_default: "sumo"
veh_state_control: "control"
veh_state_intersection: "intersection"
veh_state_out: "sumo"

zone_control_size: 500
zone_intersection_size: 100

collision_distance_thresh: 20  # needs tuning

veh_col_white: [255, 255, 255]  # default behaviour
veh_col_green: [0, 165, 0]      # in control zone
veh_col_orange: [255, 165, 0]   # adjusting trajectory
veh_col_grey: [120, 120, 120]   # intersection traversal

#Gurobi parameters begin
time_steps: 100
total_time: 10
a_min: -5
a_max: 5
#Gurobi parameters end

colliding_crossings: [[0, 4], [0, 6],[2, 4], [2, 6]]